# This config file is meant for settings that affect the whole notice page, values
# which you are expected to set up once and rarely edit after that. If you look in
# the HTML file, you will see them accessed via {{ site.var_name }}.
#
# BEFORE YOU START EDITING ANY VARIABLE, PLEASE REFER TO THE README FILE
# https://github.com/Strappazzon/tor-exit-page/blob/-/.github/README.md
#
# If you need help with YAML syntax, here are some quick references for you:
# - https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# - https://learnxinyminutes.com/docs/yaml
#
# For technical reasons, this file is NOT reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Page options
# ---------------------------------------------------------

title: "This is a Tor Exit Router"

# Exit router IP(s)
ips:
  - "198.51.100.42"
  - "198.51.100.43"

# Contact details
name: "First Last"
email: "your.email@domain.tld"
pgp: "https://example.net/pubkey.asc"

# Whether P2P ports on the exit router are blocked or not
p2p: true

# Enabled sections
sections:
  dmca: true
  ecpa: false
  credits: true

# Page generation options
# ---------------------------------------------------------

exclude:
  - LICENSE.txt
  - README.md

includes_dir: _components

sass:
  sourcemap: development
  style: compressed
