# This config file is meant for settings that affect the whole notice page, values
# which you are expected to set up once and rarely edit after that. If you look in
# the HTML file, you will see them accessed via {{ site.title }} and so on.
#
# BEFORE YOU START EDITING ANY VARIABLE, PLEASE REFER TO THE README FILE
# https://github.com/Strappazzon/tor-exit-page/blob/master/.github/README.md
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml
#
# For technical reasons, this file is NOT reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Page metadata
title: "This is a Tor Exit Router" # Mandatory. Title of the page.
#description: "This is a Tor Exit Router" # Optional. Page description.

# Page options
ips: # Optional. IP address(es) of your Tor exit router(s).
  - "198.51.100.42"
  - "198.51.100.43"
name: "First Last" # Mandatory. Your full name, name or username.
email: "your.email@domain.tld" # Mandatory. Your contact email.
#pgp: "http://example.net/publickey.asc" # Optional. URL of your PGP key.
sections:
  dmca: true # Mandatory. Wether to show the DMCA section or not.
  credits: true # Mandatory. Wether to show the Credits footer or not.

# Page generation options
destination: _output
sass:
  style: compressed
exclude:
  - build.sh
  - LICENSE.txt
