name: Build Page (Test)

on:
  push:
    branches:
      - "dev-*"
      - "dev/**"
      - "test-*"
      - "test/**"
    paths-ignore:
      - ".*/**"
      - ".*"
      - "!.ruby-version"
      - "!.tool-versions"
      - "LICENSE*"
      - "SUPPORT.md"

jobs:
  build:
    name: Build Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Setup Ruby
        env:
          BUNDLE_SPECIFIC_PLATFORM: 1
        uses: ruby/setup-ruby@v1.224.0
        with:
          bundler-cache: true

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: development
        run: |
          bundle exec jekyll build
